# Generated by Django 5.0.7 on 2024-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrequest',
            name='city1',
            field=models.CharField(default='default_city1', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='city2',
            field=models.CharField(default='default_city2', max_length=100),
        ),
    ]
